    - name: Initialize buildozer project
      run: |
        buildozer init

        # Overwrite the default buildozer.spec with minimal config
        cat <<EOF > buildozer.spec
[app]
title = HelloWorld
package.name = helloworld
package.domain = org.test
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 0.1
requirements = python3,kivy
orientation = portrait
fullscreen = 1
android.api = 33
android.ndk = 25b
android.arch = armeabi-v7a

[buildozer]
log_level = 2
warn_on_root = 1
EOF

        # Create main.py with a simple Kivy app
        cat <<EOF > main.py
from kivy.app import App
from kivy.uix.label import Label

class MyApp(App):
    def build(self):
        return Label(text="Hello, World!")

MyApp().run()
EOF
