name: Manual APK Builder

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          git clone ${{ github.server_url }}/${{ github.repository }} .
      
      - name: Set up Python and Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-dev build-essential zip
          pip install --upgrade pip
          pip install buildozer

      - name: Create spec and app
        run: |
          echo '[app]
          title = HelloWorld
          package.name = helloworld
          package.domain = org.test
          source.dir = .
          source.include_exts = py,png,jpg,kv,atlas
          version = 0.1
          requirements = python3,kivy
          orientation = portrait
          fullscreen = 1
          android.api = 33
          android.ndk = 25b
          android.arch = armeabi-v7a

          [buildozer]
          log_level = 2
          warn_on_root = 1' > buildozer.spec

          echo 'from kivy.app import App
          from kivy.uix.label import Label
          class MyApp(App):
              def build(self):
                  return Label(text="Hello, World!")
          MyApp().run()' > main.py

      - name: Build APK
        run: |
          buildozer android debug

      - name: Base64 encode APK (print to log)
        run: |
          echo "::group::APK Base64 (copy/paste and decode)"
          base64 bin/helloworld-0.1-debug.apk
          echo "::endgroup::"
